spring:
  application:
    name: psdfs
  web:
    resources:
      static-locations: classpath:/static/, classpath:/resources/static/

psdfs:
  path: ${user.home}/psdfs
  autoMd5: true
  group: C8090
  topic: psdfs
  syncBackup: false
  backupUrl: http://localhost:8091/upload
  downloadUrl: http://localhost:8090/download